# Ansible Configuration Management at Scale — lesson m05l05 — Testing With Molecule
# https://learnsome.tech/courses/ansible-course/watch?lesson=m05l05
# © LearnSome.tech
---
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
