# Ansible Configuration Management at Scale — lesson m02l03 — Dynamic Inventory
# https://learnsome.tech/courses/ansible-course/watch?lesson=m02l03
# © LearnSome.tech
---
plugin: ansible.builtin.constructed
strict: false
keyed_groups:
  - key: role
    prefix: role
  - key: tier
    prefix: tier
