# Ansible Configuration Management at Scale — lesson m05l02 — Writing A Role
# https://learnsome.tech/courses/ansible-course/watch?lesson=m05l02
# © LearnSome.tech
---
- name: Configure the site
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: web
      vars:
        site_name: Training site
